### PR TITLE
feat: add onSuccess and onError hooks in useQuery function

### LINKED ISSUE #189: Feature request: hooks for data fetch
Hi @logaretm,

First of all, this library is great job.

## Clear and concise description of the problem
When we use fetching APIs like fetch, axios or villus, we need almost all the time to work with data, specially setting mapping response data.
Currently, the only solution i found to do that with villus is using watcher and i find this not optimize:

```
const { data, isDone } = useQuery({
  query: myQuery,
  variables: ...
})
watch(isDone, (value), {
  if (value && data.value)
    mapAndSetMyData(data.value)
})
```

## Suggested solution
Add hooks like onSuccess, onError like this is setup on [Apollo](https://v4.apollo.vuejs.org/guide-composable/query.html#event-hooks)

I think this is a small feature that will help a lot.
What do you think about it ?

### PR DESCRIPTION
**Pull request by jbaubree**
Fixes #189 

@logaretm i hope this will be helpful, feel free to update this PR as needed or remove it if you think this is not a wanted feature.

### CODE REVIEW

**Comment by logaretm** [comment]
Interesting addition, I don't mind since its not really a big bundle increase and maybe is a better API than people having to watch `data` and `error` although that is what I have been doing.

Can you add tests to this?

**Comment by jbaubree** [comment]
Thanks @logaretm, i just added tests for this hooks 👌

**Review by logaretm — COMMENTED** [review]
Sorry it took a while to review this again, got a lot on my plate lately. So this looks good but wanted to run something by you first.

What do you think if we change the API to look like this:

```ts
import { useQuery } from 'villus';

const { onSuccess } = useQuery({
  query: GetPostById,
  variables,
});

onSuccess(() => {
  // do stuff
});
```


It allows for a few things:

- Lazy registration of such hooks
- Multiple registrations of such hooks
- Being able to pass them around to delegate registration to other functions/components/etc.

It feels nicer than passing it in the query options and I have seen this pattern getting traction in composition API libraries. What do you think?

**Comment by jbaubree** [comment]
Well, what you are thinking about is good. I personally think that the need to pass to other function or anything around this are each cases and can simply be override with a composable.
I like the way we can write code with the integration i wrote because for two reasons:
- this is simple to adapt and integrate on useQuery composable
- we can structure code like this that i think is more readable :

```
// All refs
const items = ref<User[]>([])
const nbItems = ref(0)

// All computed
const skip = computed(() => (currentPage.value - 1) * itemsPerPage.value)
const getUsersQuery = computed(() => USERS_GET_QUERY(skip.value)

// All utilities with impacts on refs
const { data, loading } = useQuery<{ users: UserCollectionSegment; roles: Role[] }>({
  query: getUsersQuery,
  onSuccess: ({ users, roles }) => {
    items.value = users.items ?? []
    nbItems.value = users.totalCount
  },
})
const { execute: updateUser } = useMutation<{ editUser: User }>({
  query: USER_EDIT_MUTATION,
  onSuccess: () => {
    notificationBus.emit({ variant: 'success', title: '.............' })
  },
})

// functions
function onRowClick(user: User) {
  ...
}
function onCheckboxClick(id: string) {
  ...
}

etc...
```

I'm using this way to write code because i'm using VueUse too and [useAxios](https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/index.ts) is wrote like this.

I totally agree with you with the fact that your proposition is a really good way too. If you think is will be better, it will be ok for me 👍

**Comment by logaretm** [comment]
Yep, it always can be added later without breaking changes so all good, will tag this in a release now. Thank you for the contribution!

**Pull request merged**
